/*
* This is a file generated by GBuf wizard.
* Please do not edit this file!
* Generated time: 06/04/2014 19:30:51
* Version: Primace 6.0 master
* Wizard name: GBuf 1.1a
*
*/
// ============================================================
// File Name: gbuf_v1_1.v
// IP core : gbuf
// Device name: M7A12N0F484C7
// ============================================================

module gbuf_v1_1(
    I,
    O
);

input I;
output O;

GBUF u_gbuf (
        .in (I),
        .out (O)
);

endmodule

// ============================================================
//                  gbuf Setting
//
// Warning: This part is read by Primace, please don't modify it.
// ============================================================
// Device          : M7A12N0F484C7
// Module          : gbuf_v1_1
// IP core         : gbuf
// IP Version      : 1_1

