/*
* This is a file generated by LVDS_TX wizard.
* Please do not edit this file!
* Generated time: 05/21/2014 19:46:44
* Version: Primace 6.0 master
* Wizard name: LVDS_TX 1.0a
*
*/
// ============================================================
// File Name: lvds_tx_v1.v
// IP core : lvds_tx
// Device name: M7A12N0F484C7
// ============================================================

module lvds_tx_v1(
    clk,
    rstn,
    clk_out_p,
    clk_out_n,
    tx_out_p,
    tx_out_n,
    tx_sclk,
    tx_out,
    tx_data_align_rstn
);

input clk;
input rstn;
output clk_out_p;
output clk_out_n;
output [3:0] tx_out_p;
output [3:0] tx_out_n;
output tx_sclk;
input [27:0] tx_out;
input tx_data_align_rstn;

wire pll_clkin0;
wire pll_clkout0;
wire pll_clkout1;
wire tx_sclk;
wire tx_eclk;
assign pll_clkin0 = clk;
assign tx_sclk = pll_clkout0;
assign tx_eclk = pll_clkout1;

M7S_PLL #(
        .sel_fbpath (1'b0),
        .pll_fbck_del (4'b0000),
        .pll_sel ("auto"),
        .pwrmode (2'b01),
        .rst_pll_sel (2'b00),
        .pll_divm (8'b01011010),
        .pll_divn (8'b00000001),
        .pll_divc0 (8'b00001101),
        .pll_divc1 (8'b00000011),
        .pll_divc2 (8'b00001000),
        .pll_divc3 (8'b00001000),
        .pll_divmp (3'b000),
        .pll_mken0 (1'b1),
        .pll_mken1 (1'b1),
        .pll_mken2 (1'b0),
        .pll_mken3 (1'b0),
        .pll_bps0 (1'b0),
        .pll_bps1 (1'b0),
        .pll_bps2 (1'b0),
        .pll_bps3 (1'b0),
        .pll_co0dly (8'b00000000),
        .pll_co1dly (8'b00000000),
        .pll_co2dly (8'b00000000),
        .pll_co3dly (8'b00000000),
        .pll_sel_c0phase (3'b000),
        .pll_sel_c1phase (3'b000),
        .pll_sel_c2phase (3'b000),
        .pll_sel_c3phase (3'b000),
        .dyn_pll_rst (1'b0),
        .dyn_pll_pwrdown (1'b0),
        .pll_mp_autor_en (1'b0),
        .pll_lpf (2'b00),
        .pll_vrsel (2'b00),
        .pll_cpsel_cr (2'b11),
        .pll_cpsel_fn (3'b100),
        .pll_kvsel (2'b11),
        .pll_fldd (2'b11),
        .pll_force_lock (1'b0),
        .pll_atest_en (1'b0),
        .pll_dtest_en (1'b0),
        .pll_atest_sel (1'b0),
        .pll_dtest_sel (1'b0),
        .pll_bp_dvdd12 (1'b0),
        .pll_divfb (1'b0),
        .pll_cksel (1'b0),
        .pll_ck_switch_en (1'b0),
        .pll_lkd_tol (1'b0),
        .pll_lkd_hold (1'b0),
        .pll_ssen (1'b0),
        .pll_ssrg (2'b01),
        .pll_ssdivh (2'b00),
        .pll_ssdivl (8'b00000000),
        .pll_bk (2'b00),
        .amux_sel (6'b000000),
        .cfg_nc (3'b000),
        .cfg_ldo_cfg (5'b00000)
)
pll_u0 (
        .clkin0 (pll_clkin0),
        .clkin1 (),
        .fbclkin (),
        .pwrdown (),
        .pllrst (),
        .fp_pll_rst (),
        .ACTIVECK (),
        .CKBAD0 (),
        .CKBAD1 (),
        .clkout0 (pll_clkout0),
        .clkout1 (pll_clkout1),
        .clkout2 (),
        .clkout3 (),
        .locked ()
);

M7S_IO_LVDS #(
        .ldr_cfg (4'b1111),
        .td_cfg (4'b1000),
        .term_diff_en_cfg (1'b1),
        .lvds_tx_en_cfg (1'b1),
        .cfg_sclk_gate_sel_0 (1'b1),
        .cfg_eclk_gate_sel_0 (1'b1),
        .cfg_eclk90_gate_sel_0 (1'b1),
        .cfg_eclk90_en_0 (1'b1),
        .cfg_eclk_en_0 (1'b1),
        .cfg_sclk_en_0 (1'b1),
        .cfg_d_en_0 (1'b0),
        .cfg_gear_0 (1'b1),
        .cfg_oen_sel_0 (2'b00),
        .cfg_od_sel_0 (2'b11),
        .cfg_sclk_gate_sel_1 (1'b1),
        .cfg_eclk_gate_sel_1 (1'b1),
        .cfg_eclk90_gate_sel_1 (1'b1),
        .cfg_eclk90_en_1 (1'b1),
        .cfg_eclk_en_1 (1'b1),
        .cfg_sclk_en_1 (1'b1),
        .cfg_d_en_1 (1'b0),
        .cfg_gear_1 (1'b1),
        .cfg_slave_en_1 (1'b1),
        .cfg_gear_mode7 (1'b1),
        .cfg_txd0_inv_0 (1'b1),
        .cfg_txd1_inv_0 (1'b1),
        .cfg_txd2_inv_0 (1'b0),
        .cfg_txd3_inv_0 (1'b0),
        .cfg_txd0_inv_1 (1'b0),
        .cfg_txd1_inv_1 (1'b1),
        .cfg_txd2_inv_1 (1'b1),
        .cfg_txd3_inv_1 (1'b0)
)
u_lvds_tx_clk (
        .id_1 (),
        .id_0 (),
        .id_q_0 (),
        .id_q_1 (),
        .align_rstn (tx_data_align_rstn),
        .alignwd (1'b0),
        .clk_en_1 (),
        .clk_en_0 (),
        .geclk90 (),
        .geclk (tx_eclk),
        .od_d_1 (),
        .od_d_0 (),
        .oen_1 (),
        .oen_0 (),
        .clk_0 (tx_sclk),
        .clk_1 (tx_sclk),
        .rstn_0 (),
        .rstn_1 (),
        .setn_0 (),
        .setn_1 (),
        .PAD1 (clk_out_n),
        .PAD0 (clk_out_p)
);

M7S_IO_LVDS #(
        .ldr_cfg (4'b1111),
        .td_cfg (4'b1000),
        .term_diff_en_cfg (1'b1),
        .lvds_tx_en_cfg (1'b1),
        .cfg_sclk_gate_sel_0 (1'b1),
        .cfg_eclk_gate_sel_0 (1'b1),
        .cfg_eclk90_gate_sel_0 (1'b1),
        .cfg_eclk90_en_0 (1'b1),
        .cfg_eclk_en_0 (1'b1),
        .cfg_sclk_en_0 (1'b1),
        .cfg_d_en_0 (1'b1),
        .cfg_gear_0 (1'b1),
        .cfg_oen_sel_0 (2'b00),
        .cfg_od_sel_0 (2'b11),
        .cfg_sclk_gate_sel_1 (1'b1),
        .cfg_eclk_gate_sel_1 (1'b1),
        .cfg_eclk90_gate_sel_1 (1'b1),
        .cfg_eclk90_en_1 (1'b1),
        .cfg_eclk_en_1 (1'b1),
        .cfg_sclk_en_1 (1'b1),
        .cfg_d_en_1 (1'b1),
        .cfg_gear_1 (1'b1),
        .cfg_slave_en_1 (1'b1),
        .cfg_gear_mode7 (1'b1)
)
u_lvds_tx_0 (
        .id_1 (),
        .id_0 (),
        .id_q_0 (),
        .id_q_1 (),
        .align_rstn (tx_data_align_rstn),
        .alignwd (),
        .clk_en_1 (),
        .clk_en_0 (),
        .geclk90 (),
        .geclk (tx_eclk),
        .od_d_1 ({1'b0, tx_out[6:4]}),
        .od_d_0 ({tx_out[3:0]}),
        .oen_1 (),
        .oen_0 (),
        .clk_0 (tx_sclk),
        .clk_1 (tx_sclk),
        .rstn_0 (),
        .rstn_1 (),
        .setn_0 (),
        .setn_1 (),
        .PAD1 (tx_out_n[0]),
        .PAD0 (tx_out_p[0])
);

M7S_IO_LVDS #(
        .ldr_cfg (4'b1111),
        .td_cfg (4'b1000),
        .term_diff_en_cfg (1'b1),
        .lvds_tx_en_cfg (1'b1),
        .cfg_sclk_gate_sel_0 (1'b1),
        .cfg_eclk_gate_sel_0 (1'b1),
        .cfg_eclk90_gate_sel_0 (1'b1),
        .cfg_eclk90_en_0 (1'b1),
        .cfg_eclk_en_0 (1'b1),
        .cfg_sclk_en_0 (1'b1),
        .cfg_d_en_0 (1'b1),
        .cfg_gear_0 (1'b1),
        .cfg_oen_sel_0 (2'b00),
        .cfg_od_sel_0 (2'b11),
        .cfg_sclk_gate_sel_1 (1'b1),
        .cfg_eclk_gate_sel_1 (1'b1),
        .cfg_eclk90_gate_sel_1 (1'b1),
        .cfg_eclk90_en_1 (1'b1),
        .cfg_eclk_en_1 (1'b1),
        .cfg_sclk_en_1 (1'b1),
        .cfg_d_en_1 (1'b1),
        .cfg_gear_1 (1'b1),
        .cfg_slave_en_1 (1'b1),
        .cfg_gear_mode7 (1'b1)
)
u_lvds_tx_1 (
        .id_1 (),
        .id_0 (),
        .id_q_0 (),
        .id_q_1 (),
        .align_rstn (tx_data_align_rstn),
        .alignwd (),
        .clk_en_1 (),
        .clk_en_0 (),
        .geclk90 (),
        .geclk (tx_eclk),
        .od_d_1 ({1'b0, tx_out[13:11]}),
        .od_d_0 ({tx_out[10:7]}),
        .oen_1 (),
        .oen_0 (),
        .clk_0 (tx_sclk),
        .clk_1 (tx_sclk),
        .rstn_0 (),
        .rstn_1 (),
        .setn_0 (),
        .setn_1 (),
        .PAD1 (tx_out_n[1]),
        .PAD0 (tx_out_p[1])
);

M7S_IO_LVDS #(
        .ldr_cfg (4'b1111),
        .td_cfg (4'b1000),
        .term_diff_en_cfg (1'b1),
        .lvds_tx_en_cfg (1'b1),
        .cfg_sclk_gate_sel_0 (1'b1),
        .cfg_eclk_gate_sel_0 (1'b1),
        .cfg_eclk90_gate_sel_0 (1'b1),
        .cfg_eclk90_en_0 (1'b1),
        .cfg_eclk_en_0 (1'b1),
        .cfg_sclk_en_0 (1'b1),
        .cfg_d_en_0 (1'b1),
        .cfg_gear_0 (1'b1),
        .cfg_oen_sel_0 (2'b00),
        .cfg_od_sel_0 (2'b11),
        .cfg_sclk_gate_sel_1 (1'b1),
        .cfg_eclk_gate_sel_1 (1'b1),
        .cfg_eclk90_gate_sel_1 (1'b1),
        .cfg_eclk90_en_1 (1'b1),
        .cfg_eclk_en_1 (1'b1),
        .cfg_sclk_en_1 (1'b1),
        .cfg_d_en_1 (1'b1),
        .cfg_gear_1 (1'b1),
        .cfg_slave_en_1 (1'b1),
        .cfg_gear_mode7 (1'b1)
)
u_lvds_tx_2 (
        .id_1 (),
        .id_0 (),
        .id_q_0 (),
        .id_q_1 (),
        .align_rstn (tx_data_align_rstn),
        .alignwd (),
        .clk_en_1 (),
        .clk_en_0 (),
        .geclk90 (),
        .geclk (tx_eclk),
        .od_d_1 ({1'b0, tx_out[20:18]}),
        .od_d_0 ({tx_out[17:14]}),
        .oen_1 (),
        .oen_0 (),
        .clk_0 (tx_sclk),
        .clk_1 (tx_sclk),
        .rstn_0 (),
        .rstn_1 (),
        .setn_0 (),
        .setn_1 (),
        .PAD1 (tx_out_n[2]),
        .PAD0 (tx_out_p[2])
);

M7S_IO_LVDS #(
        .ldr_cfg (4'b1111),
        .td_cfg (4'b1000),
        .term_diff_en_cfg (1'b1),
        .lvds_tx_en_cfg (1'b1),
        .cfg_sclk_gate_sel_0 (1'b1),
        .cfg_eclk_gate_sel_0 (1'b1),
        .cfg_eclk90_gate_sel_0 (1'b1),
        .cfg_eclk90_en_0 (1'b1),
        .cfg_eclk_en_0 (1'b1),
        .cfg_sclk_en_0 (1'b1),
        .cfg_d_en_0 (1'b1),
        .cfg_gear_0 (1'b1),
        .cfg_oen_sel_0 (2'b00),
        .cfg_od_sel_0 (2'b11),
        .cfg_sclk_gate_sel_1 (1'b1),
        .cfg_eclk_gate_sel_1 (1'b1),
        .cfg_eclk90_gate_sel_1 (1'b1),
        .cfg_eclk90_en_1 (1'b1),
        .cfg_eclk_en_1 (1'b1),
        .cfg_sclk_en_1 (1'b1),
        .cfg_d_en_1 (1'b1),
        .cfg_gear_1 (1'b1),
        .cfg_slave_en_1 (1'b1),
        .cfg_gear_mode7 (1'b1)
)
u_lvds_tx_3 (
        .id_1 (),
        .id_0 (),
        .id_q_0 (),
        .id_q_1 (),
        .align_rstn (tx_data_align_rstn),
        .alignwd (),
        .clk_en_1 (),
        .clk_en_0 (),
        .geclk90 (),
        .geclk (tx_eclk),
        .od_d_1 ({1'b0, tx_out[27:25]}),
        .od_d_0 ({tx_out[24:21]}),
        .oen_1 (),
        .oen_0 (),
        .clk_0 (tx_sclk),
        .clk_1 (tx_sclk),
        .rstn_0 (),
        .rstn_1 (),
        .setn_0 (),
        .setn_1 (),
        .PAD1 (tx_out_n[3]),
        .PAD0 (tx_out_p[3])
);

endmodule

// ============================================================
//                  lvds_tx Setting
//
// Warning: This part is read by Primace, please don't modify it.
// ============================================================
// Device          : M7A12N0F484C7
// Module          : lvds_tx_v1
// IP core         : lvds_tx
// IP Version      : 1

// ChannelNum      : 4
// SerialFactor    : 7
// UseClken        : false
// ExternalPll     : false
// InputFreq       : 20
// SclkFreq        : 65
