/*
* This is a file generated by Power On Reset wizard.
* Please do not edit this file!
* Generated time: 06/04/2014 19:24:31
* Version: Primace 6.0 master
* Wizard name: Power On Reset 1.1a
*
*/
// ============================================================
// File Name: por_v1_1.v
// IP core : por
// Device name: M7A12N0F484C7
// ============================================================

module por_v1_1(
    O
);

output O;

M7S_POR u_por (
        .z0 (O)
);

endmodule

// ============================================================
//                  por Setting
//
// Warning: This part is read by Primace, please don't modify it.
// ============================================================
// Device          : M7A12N0F484C7
// Module          : por_v1_1
// IP core         : por
// IP Version      : 1_1

